services:
  backend:
    build:
      context: ./backend
    container_name: poobalasingham-backend
    ports:
      - "3050:5000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://72.60.233.61:3050/api
    container_name: poobalasingham-frontend
    ports:
      - "3040:3000"
    depends_on:
      - backend
    restart: unless-stopped