services:
  backend:
    build:
      context: ./backend
    container_name: poobalasingham-backend
    network_mode: host
    env_file:
      - ./backend/.env
    environment:
      DATABASE_HOST: 192.168.0.1
      DATABASE_PORT: 15432
      PORT: 3050
    restart: unless-stopped

  frontend:
  build:
    context: ./frontend
    args:
      NEXT_PUBLIC_API_URL: http://72.60.233.61:3050/api
      NEXT_PUBLIC_API_BASE_URL: http://72.60.233.61:3050/api
  container_name: poobalasingham-frontend
  ports:
    - "3040:3000"
  depends_on:
    - backend
  restart: unless-stopped